[package]
name = "user_points_v3"
version = "1.0.0"
authors = []

[addresses]
user_points_v3  = 'Wallet Address'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git",subdir = "aptos-move/framework/aptos-framework",rev = "testnet"}